-- INSERT USERS
INSERT INTO sql_catalog.users (id_role, username, password, first_name, last_name, email) VALUES (4, 'joby17', 'joby17', 'Jordan', 'Byrne', 'jordan.byrne@email.com'),
(4, 'osco47', 'osco47', 'Oscar', 'Cox', 'oscar.cox@email.com'),
(4, 'frja64', 'frja64', 'Frederick', 'Jackson', 'frederick.jackson@email.com'),
(3, 'reda65', 'reda65', 'Reece', 'Dawson', 'reece.dawson@email.com'),
(3, 'hama67', 'hama67', 'Harry', 'Matthews', 'harry.matthews@email.com'),
(3, 'maca14', 'maca14', 'Mason', 'Carpenter', 'mason.carpenter@email.com'),
(3, 'dach80', 'dach80', 'Dario', 'Chambers', 'dario.chambers@email.com'),
(3, 'dala86', 'dala86', 'Darren', 'Lancaster', 'darren.lancaster@email.com'),
(3, 'loca23', 'loca23', 'London', 'Cantu', 'london.cantu@email.com'),
(3, 'juch33', 'juch33', 'Julien', 'Church', 'julien.church@email.com'),
(3, 'visu71', 'visu71', 'Victoria', 'Sutton', 'victoria.sutton@email.com'),
(3, 'lael20', 'lael20', 'Lara', 'Ellis', 'lara.ellis@email.com'),
(3, 'lewe17', 'lewe17', 'Lexi', 'Wells', 'lexi.wells@email.com'),
(3, 'escl20', 'escl20', 'Esme', 'Clark', 'esme.clark@email.com'),
(3, 'naal62', 'naal62', 'Naomi', 'Allen', 'naomi.allen@email.com'),
(3, 'emhe79', 'emhe79', 'Emery', 'Hendricks', 'emery.hendricks@email.com'),
(3, 'cemy69', 'cemy69', 'Cecelia', 'Myers', 'cecelia.myers@email.com'),
(3, 'ishi16', 'ishi16', 'Isabel', 'Higgins', 'isabel.higgins@email.com'),
(3, 'meca79', 'meca79', 'Meadow', 'Carlson', 'meadow.carlson@email.com'),
(3, 'ripa79', 'ripa79', 'River', 'Parry', 'river.parry@email.com'),
(3, 'lefr42', 'lefr42', 'Lesley', 'Fraser', 'lesley.fraser@email.com'),
(3, 'stbu18', 'stbu18', 'Steff', 'Burton', 'steff.burton@email.com'),
(3, 'saho26', 'saho26', 'Sammy', 'Hopkins', 'sammy.hopkins@email.com'),
(3, 'aulo27', 'aulo27', 'Aubrey', 'Lowe', 'aubrey.lowe@email.com'),
(3, 'skhi30', 'skhi30', 'Skyler', 'Hill', 'skyler.hill@email.com'),
(3, 'caes57', 'caes57', 'Caden', 'Espinoza', 'caden.espinoza@email.com'),
(3, 'roro57', 'roro57', 'Robin', 'Roberts', 'robin.roberts@email.com'),
(3, 'bepa51', 'bepa51', 'Bennie', 'Pate', 'bennie.pate@email.com'),
(3, 'hape99', 'hape99', 'Harper', 'Peck', 'harper.peck@email.com'),
(3, 'iscu75', 'iscu75', 'Isabelle', 'Cunningham', 'isabelle.cunningham@email.com'),
(3, 'kepr96', 'kepr96', 'Keira', 'Price', 'keira.price@email.com'),
(3, 'maat66', 'maat66', 'Maria', 'Atkinson', 'maria.atkinson@email.com'),
(3, 'jakh41', 'jakh41', 'Jasmine', 'Khan', 'jasmine.khan@email.com'),
(3, 'pabu73', 'pabu73', 'Paige', 'Burke', 'paige.burke@email.com'),
(3, 'kasa79', 'kasa79', 'Karen', 'Sanchez', 'karen.sanchez@email.com'),
(3, 'laho67', 'laho67', 'Laurel', 'Howard', 'laurel.howard@email.com'),
(3, 'list77', 'list77', 'Lillyana', 'Stanton', 'lillyana.stanton@email.com'),
(3, 'chri93', 'chri93', 'Cherish', 'Richardson', 'cherish.richardson@email.com'),
(3, 'elle82', 'elle82', 'Elaine', 'Levine', 'elaine.levine@email.com'),
(3, 'jopr46', 'jopr46', 'Josh', 'Price', 'josh.price@email.com'),
(3, 'hath50', 'hath50', 'Harrison', 'Thomas', 'harrison.thomas@email.com'),
(3, 'mapr46', 'mapr46', 'Mason', 'Price', 'mason.price@email.com'),
(3, 'sapo64', 'sapo64', 'Sam', 'Powell', 'sam.powell@email.com'),
(3, 'elbu38', 'elbu38', 'Ellis', 'Burke', 'ellis.burke@email.com'),
(3, 'albl11', 'albl11', 'Alonzo', 'Blanchard', 'alonzo.blanchard@email.com'),
(3, 'cawe91', 'cawe91', 'Cayden', 'Weeks', 'cayden.weeks@email.com'),
(3, 'jaev73', 'jaev73', 'Jaden', 'Everett', 'jaden.everett@email.com'),
(3, 'nopa91', 'nopa91', 'Noah', 'Padilla', 'noah.padilla@email.com'),
(3, 'nash42', 'nash42', 'Nathan', 'Sheppard', 'nathan.sheppard@email.com'),
(3, 'phan45', 'phan45', 'Phoebe', 'Andrews', 'phoebe.andrews@email.com'),
(3, 'elsm68', 'elsm68', 'Elsie', 'Smith', 'elsie.smith@email.com'),
(3, 'mejo53', 'mejo53', 'Melissa', 'Jordan', 'melissa.jordan@email.com'),
(3, 'emwa20', 'emwa20', 'Emilia', 'Wallace', 'emilia.wallace@email.com'),
(3, 'macu71', 'macu71', 'Maisy', 'Cunningham', 'maisy.cunningham@email.com'),
(3, 'adal93', 'adal93', 'Addyson', 'Alford', 'addyson.alford@email.com'),
(3, 'alem65', 'alem65', 'Alexia', 'Emerson', 'alexia.emerson@email.com'),
(3, 'olca56', 'olca56', 'Olivia', 'Castillo', 'olivia.castillo@email.com'),
(3, 'skph73', 'skph73', 'Skyla', 'Phelps', 'skyla.phelps@email.com'),
(3, 'anmu44', 'anmu44', 'Anika', 'Mueller', 'anika.mueller@email.com'),
(3, 'lahe33', 'lahe33', 'Lane', 'Henderson', 'lane.henderson@email.com'),
(3, 'tagr59', 'tagr59', 'Tanner', 'Gray', 'tanner.gray@email.com'),
(3, 'chpo43', 'chpo43', 'Charlie', 'Porter', 'charlie.porter@email.com'),
(3, 'brmc59', 'brmc59', 'Bret', 'Mcdonald', 'bret.mcdonald@email.com'),
(3, 'camo29', 'camo29', 'Caden', 'Morris', 'caden.morris@email.com'),
(3, 'stco68', 'stco68', 'Steff', 'Cox', 'steff.cox@email.com'),
(3, 'mafr14', 'mafr14', 'Maddox', 'Franks', 'maddox.franks@email.com'),
(3, 'lefi64', 'lefi64', 'Leigh', 'Fischer', 'leigh.fischer@email.com'),
(3, 'joch15', 'joch15', 'Jordan', 'Cherry', 'jordan.cherry@email.com'),
(3, 'chca81', 'chca81', 'Charlie', 'Campos', 'charlie.campos@email.com'),
(3, 'avma63', 'avma63', 'Ava', 'Marshall', 'ava.marshall@email.com'),
(3, 'fabr74', 'fabr74', 'Faith', 'Brooks', 'faith.brooks@email.com'),
(3, 'catu56', 'catu56', 'Caitlin', 'Turner', 'caitlin.turner@email.com'),
(3, 'ruho49', 'ruho49', 'Ruby', 'Howard', 'ruby.howard@email.com'),
(3, 'kafo58', 'kafo58', 'Kayla', 'Fox', 'kayla.fox@email.com'),
(3, 'adga95', 'adga95', 'Adeline', 'Garner', 'adeline.garner@email.com'),
(3, 'lamu12', 'lamu12', 'Lainey', 'Mullen', 'lainey.mullen@email.com'),
(3, 'chba98', 'chba98', 'Christina', 'Barrera', 'christina.barrera@email.com'),
(3, 'xiro46', 'xiro46', 'Ximena', 'Roth', 'ximena.roth@email.com'),
(3, 'sobo80', 'sobo80', 'Sofie', 'Bonner', 'sofie.bonner@email.com'),
(3, 'adbo25', 'adbo25', 'Adam', 'Booth', 'adam.booth@email.com'),
(3, 'kaha92', 'kaha92', 'Kayden', 'Hayes', 'kayden.hayes@email.com'),
(3, 'lufr86', 'lufr86', 'Luca', 'Fraser', 'luca.fraser@email.com'),
(3, 'alma33', 'alma33', 'Alfie', 'Martin', 'alfie.martin@email.com'),
(3, 'isbr52', 'isbr52', 'Isaac', 'Brown', 'isaac.brown@email.com'),
(3, 'vaju43', 'vaju43', 'Van', 'Juarez', 'van.juarez@email.com'),
(3, 'brmu18', 'brmu18', 'Braylen', 'Murray', 'braylen.murray@email.com'),
(3, 'gafi77', 'gafi77', 'Gauge', 'Fisher', 'gauge.fisher@email.com'),
(3, 'cobl27', 'cobl27', 'Colby', 'Blanchard', 'colby.blanchard@email.com'),
(3, 'cabr89', 'cabr89', 'Camilo', 'Brown', 'camilo.brown@email.com'),
(3, 'rewi53', 'rewi53', 'Reggie', 'Wilson', 'reggie.wilson@email.com'),
(3, 'cawa20', 'cawa20', 'Carol', 'Walsh', 'carol.walsh@email.com'),
(3, 'vahu71', 'vahu71', 'Val', 'Hussain', 'val.hussain@email.com'),
(3, 'raco12', 'raco12', 'Raylee', 'Cook', 'raylee.cook@email.com'),
(3, 'brmo98', 'brmo98', 'Brook', 'Morgan', 'brook.morgan@email.com'),
(3, 'java46', 'java46', 'Jamie', 'Valentine', 'jamie.valentine@email.com'),
(3, 'tysn18', 'tysn18', 'Tyler', 'Snider', 'tyler.snider@email.com');

-- INSERT COURSES
INSERT INTO sql_catalog.classes (class_name, description) VALUES ('Fundamentele programării şi algoritmică', 'Aenean massa metus, fermentum ut semper vel, mattis eget ligula. Praesent quis nunc quis libero tincidunt efficitur quis ac quam. Mauris porttitor luctus ligula, vel varius lectus varius sed. In eget ligula id libero semper aliquet. Vivamus in enim non turpis porttitor faucibus quis sit amet lacus'),
('Introducere în Programare', 'Nam a lobortis tortor. Sed ornare tincidunt lorem, sed hendrerit libero convallis vel. Cras eget vulputate nibh, a dapibus mauris. Nam pellentesque, odio sit amet suscipit placerat, felis dolor tempor metus, in hendrerit ipsum ligula in purus. Quisque imperdiet mi diam, a egestas erat suscipit congue'),
('Metode avansate de gestiune a documentelor şi a sistemelor de calcul', 'Maecenas lobortis mauris varius ante porta, vel tristique lectus porttitor. Nulla sit amet pharetra massa. Nam dignissim lacinia tortor. Pellentesque tincidunt congue purus sed malesuada. Cras dictum lectus magna, ut efficitur tellus tincidunt ac'),
('Programare şi structuri de date', 'Nulla leo ipsum, elementum feugiat justo eget, sodales congue ipsum. Proin sed ipsum et diam porta viverra a in lectus. Quisque elementum libero ex, pretium pellentesque nunc aliquet id. Maecenas ac dolor ut ligula mollis ornare nec vitae enim. Sed rhoncus leo nec molestie aliquam'),
('Administrarea şi securitatea reţelelor de calcul', 'Pellentesque vitae diam enim. Sed molestie sem vitae tellus elementum vehicula. Etiam ac arcu facilisis, venenatis lorem ut, sodales velit. Nullam neque dolor, viverra eget libero a, pulvinar suscipit nulla. Vivamus aliquam, purus sit amet rhoncus tempus, ante metus aliquam nulla, ut vestibulum sapien diam non felis'),
('Baze de date', 'Quisque vehicula quis tortor at viverra. Nunc dui eros, efficitur eget arcu sit amet, placerat sollicitudin erat. Suspendisse a enim sed lacus imperdiet posuere. Aenean laoreet neque vitae dui condimentum efficitur et eu lorem. Sed sagittis, augue et fringilla suscipit, velit magna pellentesque tortor, id egestas lorem neque accumsan nisi'),
('Programare orientată obiect', 'Fusce eget ligula metus. Duis eros massa, dignissim sed justo ac, molestie hendrerit massa. Curabitur enim arcu, consequat ac mauris in, porttitor facilisis magna. Quisque aliquet, nisi et malesuada finibus, neque dui varius libero, sed fringilla massa quam sagittis nisl. Phasellus viverra felis nisl, at placerat lectus condimentum vitae'),
('Tehnologii web client-side', 'Morbi blandit ligula sit amet magna efficitur feugiat. Aliquam erat volutpat. In a massa at metus lacinia semper vitae eget felis. Phasellus lobortis turpis quis lacus euismod eleifend. Proin et ex ipsum'),
('Medii de programare', 'Maecenas rhoncus est ac risus porttitor scelerisque. Fusce vulputate dapibus aliquet. Maecenas sodales auctor lorem scelerisque pulvinar. Aliquam quis finibus leo, eu gravida lorem. Nunc facilisis ipsum at pulvinar cursus'),
('Tehnologii și Framework-uri Enterprise', 'Suspendisse blandit vulputate nisi id ullamcorper. Curabitur congue suscipit mauris, non luctus metus tempor ac. Vestibulum luctus erat et nunc consectetur, sit amet condimentum justo varius. Proin in nunc accumsan, congue tellus eget, hendrerit elit. Nullam tempus placerat neque vitae vehicula'),
('Tehnologii web server-side', 'Nullam vulputate ac mi ut mattis. Nullam pharetra elementum eros sit amet cursus. Morbi at dictum erat, a porttitor nibh. Aenean commodo sit amet mi eu faucibus. Mauris malesuada dui quam, bibendum imperdiet massa ultricies eu'),
('Verificare, validare și testare automată ', 'Nulla imperdiet augue magna. Donec quis orci in massa congue pharetra. Nullam in convallis dui, eu posuere sem. In sollicitudin sapien nisl, vehicula fermentum purus fringilla lobortis. Phasellus pharetra tincidunt enim a viverra'),
('Elaborarea lucrării de absolvire', 'Vivamus a ipsum nec erat placerat accumsan. Integer blandit velit vel nisi porta, eu sollicitudin enim pulvinar. Sed arcu turpis, pharetra ac ultricies vel, pellentesque eget turpis. Curabitur eget tellus et risus auctor consequat. Etiam in suscipit ex, quis sagittis justo'),
('Introducere în Platforma.NET', 'Quisque finibus bibendum semper. Donec id tristique orci. Quisque fermentum enim leo, eget dapibus lorem euismod ut. Vestibulum sed blandit massa. Proin facilisis ullamcorper augue, in vulputate quam placerat id'),
('Practică', 'Etiam rutrum risus justo, sed tincidunt eros blandit id. In maximus mi nisi, nec interdum urna luctus sed. Curabitur placerat tortor nulla, vel sollicitudin orci consectetur quis. Vivamus a congue quam, non eleifend nulla. Suspendisse sed iaculis quam'),
('Proiect', 'Aliquam ut lorem non tellus venenatis venenatis sed ac dui. In nec tellus varius, luctus felis et, pellentesque augue. Donec eget ultricies lectus, facilisis consequat urna. Nam quis risus posuere, euismod odio blandit, placerat risus. Nunc pulvinar nisl sed vehicula rutrum'),
('Software Engineering', 'Vivamus eleifend augue purus, eu dictum velit rutrum sit amet. Duis vel ullamcorper arcu. Curabitur ac augue sed enim mollis semper. Duis feugiat ac leo a maximus. Sed vestibulum ipsum ex, in commodo odio fringilla eu');
